### PR TITLE
Initial porting for mbed

### PR DESCRIPTION
**Pull request by smoriemb**
As I've reported below, I have some trivial problems to compile your mros2 for Mbed environment.
https://www.slideshare.net/smorita1/mros2-on-mbed

We know to implement an OS abstraction layer for the potability. But, it might be beneficial to port it , without such a layer, to another OS directly, as a first step.

### CODE REVIEW

**Comment by takasehideki** [comment]
@smoriemb thank you so much for your contribution!!

I have one question to your commit, because I'm not so familiar with micro-CDR.
Why did you modify `#include <ucdr/types/string.h>` to `#include <ucdr/types/cdr_string.h>`?
Is it generally better to use `cdr_string.h` to handle String message for ROS2/DDS communication?
https://github.com/mROS-base/embeddedRTPS/pull/6/files#diff-5d1607a038f495dff32e5f4cad1145f56db8241cf21e4ab440507b1082a597b0

**Comment by smoriemb** [comment]
>Why did you modify #include <ucdr/types/string.h> to #include <ucdr/types/cdr_string.h>?
>Is it generally better to use cdr_string.h to handle String message for ROS2/DDS communication?

It is not common, I think. This modification is just a workaround for the Web  compiler.
As I said in the commit message, the Web compiler has some problem in the header search path.
It seems to confuse the "string.h" above with "string.h" of the standard library.
https://github.com/ARMmbed/mbed-cli/issues/917

I found this problem only in the Web compiler, and there is no problem with CLI2(GCC).
So, if we finally decide to give up the support for the Web compiler, this modification will no longer be needed.

**Comment by takasehideki** [comment]
Hmmm, I'm thinking deeply. Renaming third-party files just for the Mbed web compiler doesn't seem reasonable,,,

**Comment by takasehideki** [comment]
I found Micro-CDR/include/ucdr/types/string.h is no longer included the latest version of Micro-CDR officially published by eProsima.
https://github.com/eProsima/Micro-CDR/tree/master/include/ucdr

And also, header files seemed to be merged to one file.
https://github.com/eProsima/Micro-CDR/commit/1f04882c3e2713d2da6e54798e8f27664795584f#diff-9afa999489aaed4e8a94abb6e5de2470cdd2459e0f3f36b1e43bf10b5bc4a5c3

I think that our possible options are 1) to allow file renaming and 2) to follow the update to Micro-CDR.
I sent questions as an issue to embeddedRTPS developer team.
https://github.com/embedded-software-laboratory/embeddedRTPS/issues/7

**Comment by takasehideki** [comment]
we decided to merge this PR as it is.

**Pull request merged**
